Rails/views
asanew/test-guru pull request #13
Opened 2021-11-12 12:09 UTC by asanew

2021-11-12 13:26 UTC, VidgarVii requested changes

2021-11-12 13:26 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    def index
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2021-11-12 13:26 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i(show)
для 1 экшена колбек не пишут. Ухудшает читаемость

2021-11-12 13:26 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
ссылки на внешние ресурсы следует открывать в новой вкладке

2021-11-12 13:26 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +  def current_year
м/у константой и методом отступ хорошо бы оставить

2021-11-12 13:26 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
тут очень сильная связь на внешнее состояние. Т.е. это метод будет работать только в узко специализированном контексте. В остальных случаем баг. 
Всегда безопаснее работать со входящими аргументами, а не надеяться на внешний мир.
Передавай параметрами метода сам объект вопроса. И смотри persisted?

2021-11-12 13:26 UTC, VidgarVii commented on app/views/questions/_form.html.slim
> += form_with model: models, remote: false do |f|
е нужно писать услоный блок
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (не надо ее в контроллере искать, т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2021-11-12 13:26 UTC, VidgarVii commented on app/views/questions/_questions_table.html.slim
> +  thead
хоть кто-то знает про thead

2021-11-12 13:26 UTC, VidgarVii commented on app/views/questions/_questions_table.html.slim
> +    =table_body
в конце фалов надо оставлять пустую строку, чтобы не было разрыва файла

2021-11-15 12:08 UTC, asanew commented on app/controllers/questions_controller.rb
>    def index
Вывод списка вопросов на странице теста был сделан
То, что index для QuestionsController лишний - не очевидно, запрос GET /test/1/questions имеет право на существование для получения списка вопросов теста в JSON, например

2021-11-16 05:14 UTC, merged